
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.39.0dev0+80.g409cd6d'
version_full = '409cd6d37fe1ba76438aa1a3a9c6a8adcd0ddb9d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

